server:
  port: 8083
  servlet:
    context-path: /hrMgmtSystem

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  data:
    mongodb:
      uri: mongodb://localhost:27017/HRMgmtSystem


